### ISSUE TITLE
Bug: undefined method `[]' for nil:NilClass in :mobile?

### ISSUE THREAD

**Issue by Epigene** [fnando/browser#220] opened 2016-03-14 10:21 UTC
## Description

Sometimes browser gem raises an error when using the `mobile?` method.

## How to reproduce

Unknown, which user_agents are the offending ones, but perhaps an edge-case spec on `mobile?` method with incomplete/missing headers would allow to reproduce.

## What do you expect

Browser gem not to produce errors when obscure user_agents are checked with `mobile?` Should just return false if unable to discern.

## What happened instead

Browser threw a `undefined method `[]' for nil:NilClass`

## Software:

- Rails version: 4.0.0
- Browser gem version: 2.0.1

## Backtrace

```text
ActionView::Template::Error: undefined method `[]' for nil:NilClass
…le/ruby/2.0.0/gems/browser-2.0.1/lib/browser/device.rb:  166:in `detect_mobile?'
…le/ruby/2.0.0/gems/browser-2.0.1/lib/browser/device.rb:   51:in `mobile?'
```

**Comment by fnando** [comment] 2016-03-14 10:40
Please upgrade to the latest version (v2.0.2) and check if this still happens.

**Comment by jordanful** [comment] 2016-03-17 13:44
This is happening to me with v2.0.2. 

````
irb(main):024:0> b
=> #<Browser::Chrome:0x007f09119ba2c8 @ua="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36", @accept_language=[], @device=#<Browser::Device:0x007f09119cdc38 @ua="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36", @subject=#<Browser::Device::Unknown:0x007f09119cd990 @ua="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36">>>
irb(main):025:0> b.device
=> #<Browser::Device:0x007f09119cdc38 @ua="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36", @subject=#<Browser::Device::Unknown:0x007f09119cd990 @ua="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36">>
irb(main):026:0> b.device.tv?
=> false
irb(main):027:0> b.device.mobile?
=> nil
````

**Comment by fnando** [comment] 2016-03-17 13:46
@jordanful what's happening? Looks like is working fine. If the issue is `nil`, that's correct (remeber that `nil` is a falsy value in Rubyland).

**Comment by jordanful** [comment] 2016-03-18 00:58
You're right @fnando !

**Comment by Epigene** [comment] 2016-03-18 13:09
Still getting some errors. I enclosed the call in a begin-rescue block and in recue atempted to debug with `browser.to_s` but even that throws an error.

Here is the trace

```
…e/ruby/2.0.0/gems/browser-2.0.1/lib/browser/
generic.rb:  18:in `full_version'
…ndle/ruby/2.0.0/gems/browser-2.0.1/lib/browser/
base.rb:  32:in `version'
…gems/browser-2.0.1/lib/browser/meta/
generic_browser.rb:   6:in `meta'
…ruby/2.0.0/gems/browser-2.0.1/lib/browser/meta/
base.rb:  17:in `to_a'
…ndle/ruby/2.0.0/gems/browser-2.0.1/lib/browser/
/home/deployer/apps/nordenhealth/shared/bundle/ruby/2.0.0/gems/browser-2.0.1/lib/browser/base.rb
base.rb:  20:in `block in meta'
…ndle/ruby/2.0.0/gems/browser-2.0.1/lib/browser/
base.rb:  18:in `each'
…ndle/ruby/2.0.0/gems/browser-2.0.1/lib/browser/
base.rb:  18:in `each_with_object'
…ndle/ruby/2.0.0/gems/browser-2.0.1/lib/browser/
base.rb:  18:in `meta'
…ndle/ruby/2.0.0/gems/browser-2.0.1/lib/browser/
base.rb:  28:in `to_s'
…160318114936/app/controllers/
application_controller.rb: 205:in `rescue in mobile_device?'
```

**Comment by fnando** [comment] 2016-03-18 13:10
@Epigene you're still running 2.0.1, which outdated. Try v2.0.2.

**Comment by Epigene** [comment] 2016-03-18 13:22
I could swear I updated gemfile, must have missed running bundle update, thanks for noticing!

I set up the system to dump the request object if erros happen again, perhaps it will help debug what evil haxxor devices cause this. :D

**Comment by Epigene** [comment] 2016-03-21 07:57
Assuming I have successfully updated to 2.0.2, there are still requests that produce the error.
Here is a truncated request object dump, hope you can gain some insight.
https://gist.github.com/Epigene/e4e14f84d9dac621914e

**Comment by fnando** [comment] 2016-03-21 10:37
@Epigene I can't see the user agent in that Gist. Can you get it? In Rails is available under `request.user_agent`. Maybe is some sort of partial user agent that is triggering the exception?

**Comment by fnando** [comment] 2016-03-21 10:39
@Epigene also the full backtrace would be nice (I can't see which method triggered that exception, what's the code path, etc).

**Comment by Epigene** [comment] 2016-03-21 15:58
I will see if I can get the exception trace and request.user_agent portion. Unfortunately, it is quite difficult to communicate an unadulterated request object because it is rather large when converted to plaintext and I have to sanitize some sensitive values.

**Comment by fnando** [comment] 2016-03-21 16:29
You can try the following script for this (I didn't run it, so you should see if works as expected):

```ruby
class ApplicationController < ActionController::Base
  rescue_from Exception do |error|
    lines = error.backtrace.select {|line| line.include?("/browser/") }

    if lines.empty?
      raise error
    else
      # save/output the following variables.
      request.user_agent
      lines
    end
  end
end
```

I don't care about anything other than the code path inside browser and the user agent.

**Comment by fnando** [comment] 2016-05-03 22:49
No feedback, closing this.

**Closed by fnando** 2016-05-03 22:49 UTC
Labels: needs feedback

**Comment by ne0h** [comment] 2017-08-31 21:25
I have the same issue running browser-2.5.0 and Rails-5.0.5. What can I do to provide debug output?

Thanks in advance, Max.
